[build]

command = "composer build"
publish = "dist"

[[redirects]]
from="/posts/*"
to="/writing/:splat"

[[redirects]]
from="/presentations/*"
to="/decks/:splat"

[[redirects]]
from="/projects/*"
to="/work/:splat"
