<?php declare(strict_types=1);

/**
 * Generates the [[redirects]] section of netlify.toml from the post datasets.
 *
 * Every legacy URL form resolves to its final canonical location in a single
 * 301 hop (no chains), and every block is force = true so it shadows any file
 * the generator might still emit at a legacy path.
 *
 * Canonical policy:
 *   - archived post  -> /archive/<year>/<slug>/
 *   - active article -> /articles/<category>/<slug>/
 *   - active talk    -> /speaking/<category>/<slug>/
 *
 * Usage: php redirects.php > redirects.generated.toml
 * Paste the output into netlify.toml (see the marked section there).
 */

/**
 * @param array<string, mixed> $post
 */
function canonical(string $slug, array $post, string $type): string
{
    if (!empty($post['archived'])) {
        $year = date('Y', (int)strtotime((string)$post['date']));
        return "/archive/{$year}/{$slug}/";
    }
    return "/{$type}/{$post['category']}/{$slug}/";
}

/**
 * @param array<int, string> $froms
 */
function emit(array $froms, string $to): void
{
    foreach ($froms as $from) {
        if (rtrim($from, '/') === rtrim($to, '/')) {
            continue; // never redirect a URL to itself
        }
        printf("[[redirects]]\nfrom = \"%s\"\nto = \"%s\"\nstatus = 301\nforce = true\n\n", $from, $to);
    }
}

/** @var array<string, array<string, mixed>> $articles */
$articles = json_decode(file_get_contents('resources/data/articles-list.json'), true);
/** @var array<string, array<string, mixed>> $speaking */
$speaking = json_decode(file_get_contents('resources/data/speaking-list.json'), true);

echo "# ---------------------------------------------------------------------------\n";
echo "# Host normalization: force apex + https. Also set the Netlify primary domain\n";
echo "# (Domain settings) so the dashboard-level redirect is a 301 as well.\n";
echo "# ---------------------------------------------------------------------------\n\n";
emit(['https://www.shane.logsdon.io/*'], 'https://shane.logsdon.io/:splat');
emit(['https://shanelogsdon.com/*'], 'https://shane.logsdon.io/:splat');
emit(['https://www.shanelogsdon.com/*'], 'https://shane.logsdon.io/:splat');

echo "# ---------------------------------------------------------------------------\n";
echo "# Per-slug canonical redirects (generated by redirects.php). Single 301 hop.\n";
echo "# ---------------------------------------------------------------------------\n\n";

foreach ($articles as $slug => $post) {
    $to = canonical($slug, $post, 'articles');
    $froms = ["/writing/{$slug}", "/posts/{$slug}", "/articles/{$slug}"];
    if (!empty($post['archived'])) {
        $froms[] = "/articles/{$post['category']}/{$slug}";
    }
    emit($froms, $to);
}

foreach ($speaking as $slug => $post) {
    $to = canonical($slug, $post, 'speaking');
    $froms = ["/presentations/{$slug}", "/decks/{$slug}", "/speaking/{$slug}"];
    if (!empty($post['archived'])) {
        $froms[] = "/speaking/{$post['category']}/{$slug}";
    }
    emit($froms, $to);
}

echo "# ---------------------------------------------------------------------------\n";
echo "# Wildcard catch-alls. Keep LAST: only hit for slugs not enumerated above.\n";
echo "# ---------------------------------------------------------------------------\n\n";
emit(['/posts/*'], '/articles/:splat');
emit(['/writing/*'], '/articles/:splat');
emit(['/presentations/*'], '/speaking/:splat');
emit(['/decks/*'], '/speaking/:splat');
emit(['/projects/*'], '/work/:splat');
